# Generated by Django 4.0.1 on 2022-01-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='quantity',
        ),
    ]
